### ISSUE TITLE
missing file fftw3.f03

### ISSUE THREAD

**Issue by libuda** [hornekyle/CommonModules#2]
When I try to compile  the stuff I run into an error message that `include 'fftw3.f03'` is not found. It is used within src/fftw3.f90.

How do I get fftw3.f03?

**Comment by hornekyle** [comment]
I get fftw3.f03 from the fftw package on Arch linux. I think that Debian's 
libfftw3-dev probably also includes it. On Arch it is located at /usr/include/
fftw3.f03, and I assume that the location would be similar on other platforms.

CMakeLists.txt:94-99 includes the logic to find the file. It could be that this 
may need to be improved for better compatibility across distributions.

I'm glad to see your interest in my library.

**Comment by libuda** [comment]
Ok. Thx. 
Was not aware that fftw3 is a separate package. According to
`https://stackoverflow.com/questions/14850498/how-to-install-the-fftw3-package-of-r-in-ubuntu-12-04`
I installed the package using
`sudo apt-get install fftw3 fftw3-dev pkg-config`
At least that helped me to get fftw3.f90 compiled :)
Thx again for the fast response
