### ISSUE TITLE
Can't open module file ‘plplot.mod’ for reading at (1): No such file or directory

### ISSUE THREAD

**Issue by libuda** [hornekyle/CommonModules#3]
Hi,
run into an issue that the module file `plplot.mod` cannot be found during the compilation process. It is required by `CMakeFiles/CommonModules.dir/src/plplotlib/plplotlibBase.f90`.

I have installed the plplot package under
`~myhome/src/plplot-5.13.0/build/./bindings/fortran/plplot.mod`. 

How can I tell the cmake system to search for the package at my location?

**Comment by hornekyle** [comment]
I have not previously tried to use a non-standard location for plplot, but the 
following should work:

1. Set these variables on the command line when calling cmake for the first 
time.
	PLPLOT_INCLUDE_DIRS
	PLPLOT_LIBRARY_DIRS
2. The include path needs to hold plplot.mod, while the library path needs to 
include the Fortran interface for plplot as a shared library named libplplot-
f95.

Alternatively, you could somehow configure pkg_search to find the library, but 
I'm not sure how to do that.

Also alternatively, you could modify CMakeLists.txt lines 78 to 85 to adjust 
how the plplot files are found. It currently expects pkg_search to work 
correctly.

**Comment by hornekyle** [comment]
No comment after response. Closing.
